### ISSUE TITLE
[Question] LineageOS 20

### ISSUE THREAD

**Issue by billbarni** [joel16/android_device_sony_satsuki#1]
From this repository only, can I try and port it to LineageOS 20?

Can you provide some basic steps to try and acomplish it?

**Comment by joel16** [comment]
Unfortunately there's no basic steps when it comes to building roms. I'd suggest following some build tutorial like this, but instead of building for bacon you'd be building for satsuki (Z5 Premium). https://wiki.lineageos.org/devices/bacon/build/

There's a lot that goes into building roms to put it breifly:
1) Kernel trees
2) Device trees
3) Vendor blobs

Also you can try to base your device trees using what's available for Z5 (sumire): https://github.com/Sony-MSM8994-Dev
